FROM node:18-alpine As builder
WORKDIR /app
COPY package*.json ./
run npm install 
COPY . . 
RUN npm run build



#=====================

FROM nginx:alpine AS runner
COPY  --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
