FROM node:18-alpine  
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . . 
EXPOSE 5000
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 && \
    chown -R nodejs:nodejs /app
USER nodejs
CMD ["node", "index.js"]